language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "lvyun"
  - git config user.email "yunlv.go@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GITHUB_PAGE_REF}" master:master
  # if it isn't a user/org page, please replace it with <master:gh-pages>

branches:
  only:
    - hexo
env:
 global:
   - GITHUB_PAGE_REF: github.com/nofuck/nofuck.github.io.git
   - secure: "Eh5JhFDHs/qBY8LkvznWfVYZBQ7/RGQaqrK16vC3JHpiHnnQB7BRgOpMQofBafdup5Y4UZ/SciaZmOJ9RtZWiNIbw1aFHHaZl/w4+Tukg87O/rLPf4hx6eXgsPr4MLtrB3q+a0b1rfS9p0hXYsq1fVOLZInhZVj1WixPKBhO9b4ARWgj9H337igDDn7ukzXRWctvKDOZbgdAFYB2DE6bLADmS2fu95kBwJZeebaqjzLkJ6etfTYWFUQRL51xIgZ6qeA6RAAqCNKgGx3LRfgX4BlG/Rg3NuWZNA9A3hzcU5obLKqWbRMiDCogPbFhrVz5Zf7zQIB7v/HcBNgcimKXEXfx+azitNhJoQTr/weWzJCGyPl2CMvnbXCcWgpbqIfhI5w1tXqLgza6ZpVIKpmiWQHZ5aeCwAvO0Lzb8NF+h31X1uxkvV/j/67arm9rxArMKPGfZqqVO8YeJ34EvtEApvjha4CBo/nZps1fOxi1/EQRvULyxa7gWVlksjtoS3XySuz7xZeEdihYbRQDS1Xu88IouqOYXJ3bSt19JxKteNb+VNVleqbd4llJEenVk0o0iLeInexbuCoHl8RXluTDbZ+yiZVp+11r0yo57+xMrl7eZZYLUq8D3wVpCMjQHLqMWnPe0lNnQ4kU87o7TtF5b7QHzW+wNVHr96BmExBqvNk="
